### PR TITLE
Set forward headers strategy

### PR DESCRIPTION
**Pull request by frankinspace**
Set forward header strategy to framework so the application will use X-Forward headers

Closes https://github.com/podaac/swodlr/issues/77

### CODE REVIEW

**Comment by frankinspace** [comment]
Tested in SIT by manually updating the environment variable `SERVER_FORWARDHEADERSSTRATEGY` to `FRAMEWORK`

**Comment by joshgarde** [comment]
What is the behavior of utilizing `framework` instead of `native` - eg letting Jetty handle this at a lower level instead of dealing with it at the Spring level?

**Comment by frankinspace** [comment]
> What is the behavior of utilizing `framework` instead of `native` - eg letting Jetty handle this at a lower level instead of dealing with it at the Spring level?

I tried `native` and it didn't work. Rather than dig further I tried `framework` and that seemed to do the trick. My understanding is that it adds an extra filter to the chain to process the headers so shouldn't be a huge concern.

**Comment by joshgarde** [comment]
What was the prior behavior? Wasn't `X-Forwarded-Host` working for EDL redirection?

**Comment by frankinspace** [comment]
I'm not exactly sure why it was working when there was no DNS and the api was set as the default origin. But the behavior I see now is:

When this setting is not set at all (Default: `None`) the back-end tries to hit URS sending a redirct-uri with that internal `intsvc.cloud.earthdata.nasa.gov` address.

When I changed this setting to native, I observed the same behavior.

When I changed this setting to framework, the redirect-uri changed to swodlr.podaac.sit.earthdatacloud.nasa.gov

**Comment by joshgarde** [comment]
Didn't we previously determine that was an issue of the `X-Forwarded-Host` header being set incorrectly?

**Comment by frankinspace** [comment]
Yes, but it is now set to the correct value of `swodlr.podaac.sit.earthdatacloud.nasa.gov` in cloudfront

**Review by joshgarde — APPROVED** [review]

**Pull request merged**
